[editor]
scrolloff = 20
cursorline = true
rulers = [80]
line-number = "relative"
mouse = false
color-modes = true
true-color = true
auto-completion = false

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.auto-save]
focus-lost = true

[editor.lsp]
display-inlay-hints = true
auto-signature-help = false

[editor.indent-guides]
render = true
skip-levels = 1

[editor.file-picker]
hidden = false

# Not yet in stable release
# https://github.com/helix-editor/helix/pull/13133
# [editor.inline-blame]
# show = "cursor-line"
